class OrdersModel {
  OrdersModel({
    required this.TOTALPENDINGORDERS,
    required this.TOTALORDERSDELIVERED,
    required this.PACKINGINPROCESS,
    required this.Percentage,
    required this.TOTALINBOUNDORDERS,
    required this.OUTFORDELIVERY,
    required this.TOTALORDERSCREATED,
    required this.MONTHLYSHELVESOCCUPIED,
    required this.PICKINGINPROCESS,
    required this.READYTODISPATCH,
    required this.TOTALORDERSPROCESSING,
    required this.TOTALMATERIALRECEIPTS,
    required this.WEEKLYORDERSDELIVERED,
    required this.TOTALPUTAWAYS,
    required this.READYTOPROCESS,
    required this.SKUWITHLESSTHANTENQTY,
    required this.SKUWITHZEROQTY,
  });
  late final int TOTALPENDINGORDERS;
  late final int TOTALORDERSDELIVERED;
  late final int PACKINGINPROCESS;
  late final int Percentage;
  late final int TOTALINBOUNDORDERS;
  late final int OUTFORDELIVERY;
  late final int TOTALORDERSCREATED;
  late final int MONTHLYSHELVESOCCUPIED;
  late final int PICKINGINPROCESS;
  late final int READYTODISPATCH;
  late final int TOTALORDERSPROCESSING;
  late final int TOTALMATERIALRECEIPTS;
  late final int WEEKLYORDERSDELIVERED;
  late final int TOTALPUTAWAYS;
  late final int READYTOPROCESS;
  late final int SKUWITHLESSTHANTENQTY;
  late final int SKUWITHZEROQTY;

  OrdersModel.fromJson(Map<String, dynamic> json){
    TOTALPENDINGORDERS = json['TOTAL_PENDING_ORDERS'];
    TOTALORDERSDELIVERED = json['TOTAL_ORDERS_DELIVERED'];
    PACKINGINPROCESS = json['PACKING_IN_PROCESS'];
    Percentage = json['Percentage'];
    TOTALINBOUNDORDERS = json['TOTAL_INBOUND_ORDERS'];
    OUTFORDELIVERY = json['OUT_FOR_DELIVERY'];
    TOTALORDERSCREATED = json['TOTAL_ORDERS_CREATED'];
    MONTHLYSHELVESOCCUPIED = json['MONTHLY_SHELVES_OCCUPIED'];
    PICKINGINPROCESS = json['PICKING_IN_PROCESS'];
    READYTODISPATCH = json['READY_TO_DISPATCH'];
    TOTALORDERSPROCESSING = json['TOTAL_ORDERS_PROCESSING'];
    TOTALMATERIALRECEIPTS = json['TOTAL_MATERIAL_RECEIPTS'];
    WEEKLYORDERSDELIVERED = json['WEEKLY_ORDERS_DELIVERED'];
    TOTALPUTAWAYS = json['TOTAL_PUTAWAYS'];
    READYTOPROCESS = json['READY_TO_PROCESS'];
    SKUWITHLESSTHANTENQTY = json['SKU_WITH_LESS_THAN_TEN_QTY'];
    SKUWITHZEROQTY = json['SKU_WITH_ZERO_QTY'];
  }

  Map<String, dynamic> toJson() {
    final _data = <String, dynamic>{};
    _data['TOTAL_PENDING_ORDERS'] = TOTALPENDINGORDERS;
    _data['TOTAL_ORDERS_DELIVERED'] = TOTALORDERSDELIVERED;
    _data['PACKING_IN_PROCESS'] = PACKINGINPROCESS;
    _data['Percentage'] = Percentage;
    _data['TOTAL_INBOUND_ORDERS'] = TOTALINBOUNDORDERS;
    _data['OUT_FOR_DELIVERY'] = OUTFORDELIVERY;
    _data['TOTAL_ORDERS_CREATED'] = TOTALORDERSCREATED;
    _data['MONTHLY_SHELVES_OCCUPIED'] = MONTHLYSHELVESOCCUPIED;
    _data['PICKING_IN_PROCESS'] = PICKINGINPROCESS;
    _data['READY_TO_DISPATCH'] = READYTODISPATCH;
    _data['TOTAL_ORDERS_PROCESSING'] = TOTALORDERSPROCESSING;
    _data['TOTAL_MATERIAL_RECEIPTS'] = TOTALMATERIALRECEIPTS;
    _data['WEEKLY_ORDERS_DELIVERED'] = WEEKLYORDERSDELIVERED;
    _data['TOTAL_PUTAWAYS'] = TOTALPUTAWAYS;
    _data['READY_TO_PROCESS'] = READYTOPROCESS;
    _data['SKU_WITH_LESS_THAN_TEN_QTY'] = SKUWITHLESSTHANTENQTY;
    _data['SKU_WITH_ZERO_QTY'] = SKUWITHZEROQTY;
    return _data;
  }
}